version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.5

    working_directory: ~/wikipedia_twilio

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
          - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest -v

      - deploy:
          name: deploy to zappa
          command: |
            . venv/bin/activate

            if [ "$CIRCLE_BRANCH" != "master" ]; then export ZAPPA_STAGE=dev; fi
            if [ "$CIRCLE_BRANCH" = "master" ]; then export ZAPPA_STAGE=prod; fi

            zappa package $ZAPPA_STAGE

            mkdir -p ~/.aws

            echo -e "[mislavcimpersak]" >> ~/.aws/credentials
            echo -e "aws_access_key_id = "$AWS_ACCESS_KEY_ID >> ~/.aws/credentials
            echo -e "aws_secret_access_key = "$AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials

            zappa update $ZAPPA_STAGE || zappa deploy $ZAPPA_STAGE;
