version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/wikipedia_twilio

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest -v

  deploy:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - run:
        # set ZAPPA_STAGE env var depending on current branch
        if [ "$CIRCLE_BRANCH" != "master" ]; then export ZAPPA_STAGE=dev; fi
        if [ "$CIRCLE_BRANCH" = "master" ]; then export ZAPPA_STAGE=prod; fi

        # test if .zip file can be created
        zappa package $ZAPPA_STAGE

        # set aws credentials from env vars set in web interface
        mkdir -p ~/.aws
        echo "[Admin]" >> ~/.aws/credentials
        echo "aws_access_key_id = "$AWS_ACCESS_KEY_ID >> ~/.aws/credentials
        echo "aws_secret_access_key = "$AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials

        # try to update, if the command fails do the initial deploy
        zappa update $ZAPPA_STAGE || zappa deploy $ZAPPA_STAGE;

workflows:
    version: 2
    build-deploy:
      jobs:
      - build
      - deploy:
          requires:
          - build
          filters:
            branches:
              only: master